### ISSUE TITLE
How can I test on my own images?

### ISSUE THREAD

**Issue by wangmingyang4** [jack111331/StyleFaceUV#1]
1. Thanks for your work, i found there is no enough pretrained model files in this repo. eg: 
BFM/ 										-- 放一些定義好的3DMM Model (Basel Face Model 2009)
checkpoints/ 									-- checkpoints of stylecode_to_3Dcoeff.py
checkpoints_final/ 								-- checkpoints of stylegan2_to_3d.py
checkpoints_latent2posescalar-new-sym/ 			-- checkpoints of latent_to_Pose_Scalar.py
checkpoints_latent2posescalar-new_multi-pose/ 	        -- checkpoints of latent_to_Multi_Pose_Scalar.py
2. And i wish to test on my own images. how can i do?
3. Finally, i can get the face mesh .gltf, but i want to get the face uv.png.

**Comment by jack111331** [comment]
1. Please follow the "Environment setting" section in readme.md to get all the required data and checkpoints. After that, you will find two directories "ckpt" and "data" appears in the root directory.
2. If you want to test on your own image, then you have to perform "GAN Inversion" on your image and acquire their corresponding inverted style code. This style code can then be input to our pre-trained "Stylecode to 3D Coefficients" module to get its corresponding 3DMM coefficients.
Using our "forward" method of our pre-trained StyleFaceUV Module in "model/stylegan2_texture.py", you may generate corresponding 3D model from them.
Note that we haven't tested if the style code acquired from GAN inversion is valid for generating 3D Faces.
3. The face diffuse map is also embedded in the .gltf. If you want to solely acquire the diffuse map, you can modify StyleFaceUV.save_as_gltf() to output diffuse map as image file.

**Comment by wangmingyang4** [comment]
i download data and ckpt files but the code needs something like pkl files.

**Comment by jack111331** [comment]
Could you tell me what exactly files that you're missing?
What you saw the files listed in readme_1.md are actually deprecated. They aren't necessary if you follow what we wrote in readme.md.

**Comment by wangmingyang4** [comment]
> 1. Please follow the "Environment setting" section in readme.md to get all the required data and checkpoints. After that, you will find two directories "ckpt" and "data" appears in the root directory.
> 2. If you want to test on your own image, then you have to perform "GAN Inversion" on your image and acquire their corresponding inverted style code. This style code can then be input to our pre-trained "Stylecode to 3D Coefficients" module to get its corresponding 3DMM coefficients.
>    Using our "forward" method of our pre-trained StyleFaceUV Module in "model/stylegan2_texture.py", you may generate corresponding 3D model from them.
>    Note that we haven't tested if the style code acquired from GAN inversion is valid for generating 3D Faces.
> 3. The face diffuse map is also embedded in the .gltf. If you want to solely acquire the diffuse map, you can modify StyleFaceUV.save_as_gltf() to output diffuse map as image file.

Thamks for your reply.
From Q2, i have the inverted style code (like latent code?) for my single image (a 1,18,512 np files). How can i input it to pre-trained "Stylecode to 3D Coefficients" module to get its corresponding 3DMM coefficients? I found there is a code file like stylecode_to_3D coeff.py. And im confused about using it.
In addition, I am interested in changing face pose and hope to be able to test the results quickly.
If you can add guidance details to test custom image, I would appreciate it.

**Comment by jack111331** [comment]
@wangmingyang4 
You can utilize StyleFaceUV module and [directly use its stylecode_to_3dmm_coeff_model](https://github.com/jack111331/StyleFaceUV/blob/main/model/stylegan2_texture.py#L343) member to inference 3dmm coefficient from style code(a.k.a latent code).
A demonstration is made in one of the member function in StyleFaceUV module called "save_as_gltf()". You can take it as a reference to write your own program.

As for changing the generated 3D face pose, you can change the corresponding [Pose coefficients](https://github.com/jack111331/StyleFaceUV/blob/main/model/face_renderer.py#L106) in 3DMM coefficients and leverage the pure_3dmm_model in StyleFaceUV to render the inferred 3DMM coefficients and their texture maps.

If you need more insight, please refer to [forward()](https://github.com/jack111331/StyleFaceUV/blob/main/model/stylegan2_texture.py#L349) method in StyleFaceUV module, you'll see how we render the face.
